export var blankPC = [
	{ caption: 'YES24 - POB', total: 4 }, 
	{ caption: 'Tower Record Shibuya', total: 3 },
	{ caption: 'Aladin - POB', total: 4 },
	{ caption: 'Hottracks - POB', total: 4 },
	{ caption: 'KTown4U - POB', total: 4 },
	{ caption: 'Ktown4u - FS/VC', total: 4 },
	{ caption: 'Soundwave - FS', total: 3 },
	{ caption: 'Soundwave - VC ', total: 3 },
	{ caption: 'Apple Music POB', total: 4 },
	{ caption: 'Apple Music - VC ', total: 4 },
	{ caption: 'Apple Music - FS Encore', total: 3 },
	{ caption: 'Apple Music - VC Encore', total: 3 },
	{ caption: 'Counting Star - VC', total: 3 },
	{ caption: 'MusicArt - VC', total: 3 },
	{ caption: 'MusicArt - VC 2', total: 3 },
	{ caption: 'MMT - FS', total: 4 },
	{ caption: 'MMT - VC', total: 4 },
	{ caption: 'Joeun Music - FS', total: 3 },
	{ caption: 'Joeun Music - VC', total: 3 },
	{ caption: 'JJMuse - FS', total: 3 },
	{ caption: 'JJMuse - VC', total: 3 },
	{ caption: 'JJMuse - VC Encore', total: 3 },
	{ caption: 'Danal Ent Music - VC Encore', total: 3 },
	{ caption: 'Rising Star - VC', total: 3 },
	{ caption: 'Jump Up - FS', total: 3 },
	{ caption: 'Jump Up - VC', total: 3 },
	{ caption: 'DMM - FS', total: 3 },
	{ caption: 'DMM - VC', total: 3 },
	{ caption: 'DMM - FS Encore', total: 3 },
	{ caption: 'DMM - VC Encore', total: 3 },
	{ caption: 'Makestar - FS', total: 3 },
	{ caption: 'Makestar - VC', total: 3 },
	{ caption: 'Makestar - FS Encore', total: 3 },
	{ caption: 'Makestar - VC Encore', total: 3 },
	{ caption: 'Music & Drama - VC Encore', total: 4 },
	{ caption: 'Beatroad - FS Encore', total: 3 },
	{ caption: 'Beatroad - VC Encore', total: 3 },
	{ caption: 'FLNK - FS Encore', total: 3 },
	{ caption: 'FLNK - VC Encore', total: 3 },
	{ caption: 'Everline - FS', total: 3 },
	{ caption: 'Everline - VC', total: 3 },
	{ caption: 'Everline - FS Encore', total: 3 },
	{ caption: 'Everline - VC Encore', total: 3 },
	{ caption: 'Japan mini event', total: 6 }, 
]