export var astroAlbumPC = [
  { caption: 'Spring up', total: 2 },
	{ caption: 'Summer Vibes', total: 3 },
	{ caption: 'Autumn Story - Red', total: 2 },
	{ caption: 'Autumn Story - Orange', total: 2 },
	{ caption: 'Winter Dream', total: 2 },
	{ caption: 'Dream Pt1 - Day', total: 3 },
	{ caption: 'Dream Pt1 - Night', total: 3 },
	{ caption: 'Dream Pt2 - Wind', total: 3 },
	{ caption: 'Dream Pt2 - Wish', total: 3 },
	{ caption: 'Dream Sp. Edition', total: 2 },
	{ caption: 'Rise up', total: 4 },
	{ caption: 'All Light - White', total: 4 },
	{ caption: 'All Light - Green', total: 4 },
	{ caption: 'Blue Flame - Book', total: 2 },
	{ caption: 'Blue Flame - Story', total: 2 },
	{ caption: 'One & Only', total: 2 },
	{ caption: 'Gateway - Another World', total: 2 },
	{ caption: 'Gateway - Time Traveler', total: 2 },
	{ caption: 'All Yours - You', total: 2 },
	{ caption: 'All Yours - Me', total: 2 },
	{ caption: 'All Yours - Us', total: 2 },
	{ caption: 'Switch On', total: 8 },
	{ caption: 'Restore - Staycation', total: 4 },
	{ caption: 'Restore - Vacation', total: 4 },
	{ caption: 'Drive to the Starry Road - Drive', total: 4 },
	{ caption: 'Drive to the Starry Road - Starry', total: 4 },
	{ caption: 'Drive to the Starry Road - Road', total: 4 },
]


export var astroNonAlbumPC = [
	{ caption: 'CSC Broadcast', total: 1 },
	{ caption: 'Kihno Special', total: 2 },
	{ caption: 'Rise Up - Pop up Store', total: 2 },
	{ caption: 'FM201.8', total: 1 },
	{ caption: 'All Light - Broadcast/FS', total: 4 },
	{ caption: 'All Light - JP Handshake Event', total: 4 },
	{ caption: 'Venus - Tower Records', total: 2 },
	{ caption: 'Venus - HMV', total: 1 },
	{ caption: 'Blue Flame - Concept Zone', total: 2 },
	{ caption: 'Blue Flame - Broadcast', total: 2 },
	{ caption: 'Blue Flame - FS', total: 2 },
	{ caption: 'Gateway - Japan', total: 1 },
	{ caption: 'Gateway - China', total: 1 },
	{ caption: 'Gateway - Taiwan', total: 1 },
	{ caption: 'Gateway - VC', total: 1 },
	{ caption: 'Gateway - Fancafe event', total: 1 },
	{ caption: 'All Yours - Cafe', total: 2 },
	{ caption: 'All Yours - Tower Records POB', total: 2 },
	{ caption: 'All Yours - DMM POB', total: 1 },
	{ caption: 'All Yours - DMM VC', total: 1 },
	{ caption: 'All Yours - Withdrama POB', total: 1 },
	{ caption: 'All Yours - Withdrama VC', total: 1 },
	{ caption: 'All Yours - Broadcast (Self Printed)', total: 3 },
	{ caption: 'All Yours - LuckyGO VC 1', total: 1 },
	{ caption: 'All Yours - LuckyGO VC 2', total: 1 },
	{ caption: 'All Yours - Makestar VC 1', total: 1 },
	{ caption: 'All Yours - Makestar VC 2', total: 1 },
	{ caption: 'All Yours - DMC VC', total: 1 },
	{ caption: 'All Yours - DMC Winner VC', total: 1 },
	{ caption: 'All Yours - Mihwadang VC', total: 1 },
	{ caption: 'All Yours - Mihwadang Winner VC ', total: 1 },
	{ caption: 'All Yours - Joeun VC', total: 1 },
	{ caption: 'All Yours - Joeun Winner VC', total: 1 },
	{ caption: 'All Yours - Music Korea VC', total: 1 },
	{ caption: 'All Yours - Music Korea Winner VC', total: 1 },
	{ caption: 'All Yours - Beatroad VC', total: 1 },
	{ caption: 'All Yours - Beatroad Winner VC', total: 1 },
	{ caption: 'All Yours - OTK POB', total: 1 },
	{ caption: 'All Yours - Apple Music POB', total: 1 },
	{ caption: 'All Yours - Apple Music VC 1', total: 1 },
	{ caption: 'All Yours - Apple Music VC 2', total: 1 },
	{ caption: 'All Yours - Everline POB', total: 1 },
	{ caption: 'All Yours - Everline VC 1', total: 1 },
	{ caption: 'All Yours - Everline Winner VC 1', total: 1 },
	{ caption: 'All Yours - Everline VC 2', total: 1 },
	{ caption: 'All Yours - Everline Winner VC 2', total: 1 },	
	{ caption: 'All Yours - POB Set', total: 1 },
	{ caption: 'Switch On - Tokopedia POB', total: 1 },
	{ caption: 'Switch On - Shopee VC', total: 1 },
	{ caption: 'Switch On - Beatroad VC', total: 1 },
	{ caption: 'Switch On - Mihwadang VC', total: 1 },
	{ caption: 'Switch On - Music Korea VC', total: 1 },
	{ caption: 'Switch On - DMC VC', total: 1 },
	{ caption: 'Switch On - Joeun VC', total: 1 },
	{ caption: 'Switch On - Mocket Shop POB', total: 1 },
	{ caption: 'Switch On - Withdrama POB+VC', total: 1 },
	{ caption: 'Switch On - Withdrama VC 2', total: 1 },
	{ caption: 'Switch On - Applewood POB', total: 2 },
	{ caption: 'Switch On - CLCNE POB', total: 2 },
	{ caption: 'Switch On - Broadcast (Self Printed)', total: 2 },
	{ caption: 'Switch On - DMM POB', total: 1 },
	{ caption: 'Switch On - DMM VC', total: 1 },
	{ caption: 'Switch On - Everline POB', total: 1 },
	{ caption: 'Switch On - Everline VC 1', total: 1 },
	{ caption: 'Switch On - Everline VC 2', total: 1 },
	{ caption: 'Switch On - Pop-up Store: MD', total: 1 },
	{ caption: 'Switch On - Pop-up Store: MD Purchased >5k won', total: 1 },
	{ caption: 'Switch On - Pop-up Store: Lucky Draw', total: 1 },	
	{ caption: 'Switch On - Tower Records POB', total: 4 },
	{ caption: 'Switch On - Wonderwall VC 1', total: 1 },
	{ caption: 'Switch On - Wonderwall Winner VC 1', total: 1 },
	{ caption: 'Switch On - Wonderwall VC 2', total: 1 },
	{ caption: 'Switch On - Wonderwall MD', total: 1 },
	{ caption: 'Switch On - Apple Music POB', total: 1 },
	{ caption: 'Switch On - Apple Music Lucky Draw', total: 3 },
	{ caption: 'Switch On - Apple Music VC 1', total: 1 },
	{ caption: 'Switch On - Apple Music VC 1 Winner', total: 1 },
	{ caption: 'Switch On - Apple Music VC 2', total: 1 },
	{ caption: 'Switch On - Apple Music VC 2 Winner', total: 1 },
	{ caption: 'Switch On - Apple Music VC 3', total: 1 },
	{ caption: 'Switch On - Apple Music VC 4', total: 2 },
	{ caption: 'RESTORE - CLCNE POB', total: 1 },
	{ caption: 'RESTORE - Apple Music Lucky Draw', total: 5 },
	{ caption: 'RESTORE - Apple Music FS/VC 1', total: 2 },
	{ caption: 'RESTORE - Apple Music FS/VC 2', total: 2 },
	{ caption: 'RESTORE - Apple Music FS/VC 3', total: 2 },
	{ caption: 'RESTORE - Apple Music FS/VC 4', total: 2 },
	{ caption: 'RESTORE - Apple Music VC 5', total: 2 },
	{ caption: 'RESTORE - Apple Music FS/VC 6', total: 2 },
	{ caption: 'RESTORE - Apple Music FS/VC 7', total: 2 },
	{ caption: 'RESTORE - Apple Music VC 8', total: 2 },
	{ caption: 'RESTORE - Everline FS 1', total: 1 },
	{ caption: 'RESTORE - Everline Winner FS 1', total: 1 },
	{ caption: 'RESTORE - Everline FS 2', total: 1 },
	{ caption: 'RESTORE - Everline Winner FS 2', total: 1 },
	{ caption: 'RESTORE - Everline VC 1', total: 1 },	
	{ caption: 'RESTORE - Everline VC 2', total: 1 },
	{ caption: 'RESTORE - Everline Winner VC 2', total: 1 },
	{ caption: 'RESTORE - Yihziyu VC', total: 1 },
	{ caption: 'RESTORE - Makestar VC 1', total: 2 },
	{ caption: 'RESTORE - Makestar VC 2', total: 2 },
	{ caption: 'RESTORE - Withdrama FS/VC 1', total: 2 },
	{ caption: 'RESTORE - Withdrama FS/VC 2', total: 2 },
	{ caption: 'RESTORE - JJMuze VC', total: 1 },
	{ caption: 'RESTORE - JJMuze Sp. Gift', total: 1 },
	{ caption: 'RESTORE - Music Korea VC', total: 1 },
	{ caption: 'RESTORE - DMC VC', total: 1 },
	{ caption: 'RESTORE - Joeun FS', total: 1 },
	{ caption: 'RESTORE - Mihwadang FS', total: 1 },
	{ caption: 'RESTORE - MD Staycation', total: 2 },
	{ caption: 'RESTORE - MD Vacation', total: 2 },
	{ caption: 'RESTORE - Winners Fancafe Event', total: 4 },
	{ caption: 'DTTSR - Apple Music Lucky Draw', total: 3 },
	{ caption: 'DTTSR - Apple Music VC 1', total: 1 },
	{ caption: 'DTTSR - Apple Music VC 2', total: 1 },
	{ caption: 'DTTSR - Apple Music VC 3', total: 1 },
	{ caption: 'DTTSR - Apple Music FS/VC 4', total: 1 },
	{ caption: 'DTTSR - Apple Music VC 5', total: 1 },	
	{ caption: 'DTTSR - Apple Music VC 6', total: 1 },
	{ caption: 'DTTSR - Apple Music Lucky Draw Cafe ', total: 3 },
	{ caption: 'DTTSR - Apple Music Cafe', total: 1 },
	{ caption: 'DTTSR - Ktown4u VC 1', total: 1 },
	{ caption: 'DTTSR - Ktown4u FS/VC 2', total: 1 },
	{ caption: 'DTTSR - Ktown4u Pop-up Lucky Draw', total: 2 },
	{ caption: 'DTTSR - DMM VC 1', total: 1 },
	{ caption: 'DTTSR - DMM VC 2', total:  1},
	{ caption: 'DTTSR - Withdrama / Withmuu - POB', total: 1 },
	{ caption: 'DTTSR - Withdrama / Withmuu VC 1', total: 1 },
	{ caption: 'DTTSR - Withdrama / Withmuu VC 2', total: 1 },
	{ caption: 'DTTSR - Withdrama / Withmuu FS/VC 3', total: 1 },
	{ caption: 'DTTSR - Withdrama / Withmuu VC 4', total: 1 },
	{ caption: 'DTTSR - Withdrama / Withmuu VC 5', total: 1 },
	{ caption: 'DTTSR - Withdrama / Withmuu Lucky Draw Cafe', total: 2 },
	{ caption: 'DTTSR - Synnara POB', total: 1 },
	{ caption: 'DTTSR - Tokopedia POB', total: 1 },
	{ caption: 'DTTSR - Tower Records POB', total: 2 },
	{ caption: 'DTTSR - Mu-mo Shop VC', total: 1 },
	{ caption: 'DTTSR - CB Cafe x DMM: Cookies Gift', total: 2 },
	{ caption: 'DTTSR - Broadcast Music Bank', total: 1 },
	{ caption: 'DTTSR - Broadcast Music Core', total: 1 },	
	{ caption: 'DTTSR - Broadcast Inkigayo', total: 1 },
	{ caption: 'DTTSR - Twitter event', total: 1 },
	{ caption: 'DTTSR - Showcase', total: 1 },
	{ caption: '1番好きな人にサヨナラを言おう - Loppi・HMV', total: 1 },
	{ caption: '1番好きな人にサヨナラを言おう - FC', total: 1 }
]
